version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    container_name: ordering_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  customer_service:
    build: ./customer_service
    container_name: customer_service
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/ordering_system
    depends_on:
      - mongodb

  employee_service:
    build: ./employee_service
    container_name: employee_service
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongodb:27017/ordering_system
    depends_on:
      - mongodb

volumes:
  mongo_data:
